### PR TITLE
feat: Add rubocop format

### PR DESCRIPTION
**Pull request by ttttsuboi**
can format without commands

### CODE REVIEW

**Comment by tsuyoshicho** [comment]
To: @ttttsuboi 
Thanks for your PR.

Can you separate the definitions for lint and format if you like?

**Comment by ttttsuboi** [comment]
@tsuyoshicho 

Thank you for your reply.
I tried it. 
Is this correct as you expected?

**Comment by tsuyoshicho** [comment]
Basic struct OK.

I believe you are checked rubocop option.

**Comment by ttttsuboi** [comment]
I appreciate your cooperation.

**Pull request merged**
